### ISSUE TITLE
Remove GSAP

### ISSUE THREAD

**Issue by marlonmarcello** [wethegit/wtc-perspective-card#1]
**Issue**
When this library was first created it had to support really old browsers, so we used GSAP to standardize the animation.
GSAP is a huge library and makes this simple controller way bigger than it should be.

**Solution**
We should come up with a better implementation that doesn't require us to use GSAP.
For reference: https://codepen.io/shubniggurath/pen/PowEzVb

**Comment by liamegan** [comment]
This is now done in V2
